# Generated by Django 5.0.4 on 2024-04-27 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qikdial', '0002_usermodel_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='name',
            field=models.CharField(default='admin', max_length=100),
        ),
    ]
