# Generated by Django 5.0.4 on 2024-04-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qikdial', '0005_tokenmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='parent_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
