# Generated by Django 5.0.4 on 2024-04-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qikdial', '0006_categorymodel_parent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingmodel',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
