# Generated by Django 5.0.4 on 2024-05-01 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qikdial', '0009_blogmodel_commentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
