# Generated by Django 5.0.4 on 2024-05-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qikdial', '0011_citymodel_citylistingmodel_productmodel_servicemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='citymodel',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
