# Generated by Django 5.0.4 on 2024-05-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qikdial', '0012_citymodel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicemodel',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='listingmodel',
            name='specific_city',
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='delivery_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='height',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='mode_of_service',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='refund',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='weight',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='width',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='ProductModel',
        ),
        migrations.DeleteModel(
            name='ServiceModel',
        ),
    ]
