# Generated by Django 5.0.4 on 2024-05-03 06:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qikdial', '0014_alter_amenitymodel_name_alter_citymodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingmodel',
            name='category',
        ),
        migrations.RemoveField(
            model_name='listingmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='category',
            field=models.ManyToManyField(to='qikdial.categorymodel'),
        ),
        migrations.AddField(
            model_name='listingmodel',
            name='user',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
