# Generated by Django 5.0.4 on 2024-05-03 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qikdial', '0017_alter_listingmodel_category_alter_listingmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingmodel',
            name='category',
        ),
        migrations.RemoveField(
            model_name='listingmodel',
            name='user',
        ),
    ]
