# Generated by Django 5.0.4 on 2024-05-04 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qikdial', '0021_alter_ratingmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingviewsmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
