# Generated by Django 5.0.4 on 2024-05-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qikdial', '0022_alter_listingviewsmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
