# Generated by Django 5.0.4 on 2024-05-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qikdial', '0024_contactsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='summary',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
