# Generated by Django 5.0.4 on 2024-05-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qikdial', '0025_blogmodel_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='summary',
            field=models.TextField(default=None),
        ),
    ]
