# Generated by Django 5.0.4 on 2024-05-06 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qikdial', '0026_alter_blogmodel_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='image',
            field=models.ImageField(upload_to='qikdial/uploads/blogs'),
        ),
    ]
