# Generated by Django 5.0.4 on 2024-05-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qikdial', '0027_alter_blogmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingmodel',
            name='map_address',
            field=models.TextField(default='0', null=True),
        ),
    ]
