# Generated by Django 5.0.4 on 2024-05-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qikdial', '0028_listingmodel_map_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingmodel',
            name='gstin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listingmodel',
            name='map_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listingmodel',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listingmodel',
            name='timings',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listingmodel',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
