# Generated by Django 5.0.4 on 2024-05-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qikdial', '0029_alter_listingmodel_gstin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingmodel',
            name='delivery_duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listingmodel',
            name='mode_of_service',
            field=models.CharField(blank=True, default='1', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listingmodel',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
