# Generated by Django 5.0.4 on 2024-06-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qikdial', '0030_alter_listingmodel_delivery_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquirymodel',
            name='email',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='enquirymodel',
            name='message',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='enquirymodel',
            name='mobile',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enquirymodel',
            name='name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
