# Generated by Django 5.0.4 on 2024-06-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qikdial', '0031_enquirymodel_email_enquirymodel_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsmodel',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='contactsmodel',
            name='message',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='contactsmodel',
            name='mobile',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactsmodel',
            name='name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactsmodel',
            name='subject',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
